- name: Compile jpeg, libbulletml, libmad, zlib ports
  shell: make -j {{ ansible_processor_vcpus }}
    chdir={{ psp_ports_tmp_path }}/psp-ports/{{ item }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
  with_items:
    - jpeg
    - 'libbulletml/src'
    - libmad
    - zlib

- name: Install jpeg, libbulletml, libmad, zlib ports
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
    chdir={{ psp_ports_tmp_path }}/psp-ports/{{ item }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
  with_items:
    - jpeg
    - 'libbulletml/src'
    - libmad
    - zlib

- name: Compile libpspvram, pspirkeyb, pspgl ports
  shell: make -j {{ ansible_processor_vcpus }}
    chdir={{ psp_ports_tmp_path }}/psp-ports/{{ item }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
  with_items:
    - libpspvram
    - pspirkeyb
    - pspgl

- name: Install libpspvram, pspirkeyb, pspgl ports
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
    chdir={{ psp_ports_tmp_path }}/psp-ports/{{ item }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
  with_items:
    - libpspvram
    - pspirkeyb
    - pspgl

- name: Compile libpng port
  shell: make -j {{ ansible_processor_vcpus }}
    chdir={{ psp_ports_tmp_path }}/psp-ports/libpng
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"

- name: Install libpng port
  sudo: yes
  shell: make -j {{ ansible_processor_vcpus }} install
    chdir={{ psp_ports_tmp_path }}/psp-ports/libpng
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ pspdev_path }}/bin"
